version: 0.2
phases:
    install:
        runtime-versions:
            docker: 18
    pre_build:
        commands:
        - echo "Adding dependencies"
        - yum -y install zip awscli jq
        - printenv
        - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 813995029960.dkr.ecr.ap-southeast-1.amazonaws.com
    build:
        commands:
        - make build_base
        - make build_php
        - make build_nginx
    post_build:
        commands:
        - docker tag laraveldemo_php 813995029960.dkr.ecr.ap-southeast-1.amazonaws.com/laraveldemo-php:${CODEBUILD_RESOLVED_SOURCE_VERSION}
        - docker tag laraveldemo_nginx 813995029960.dkr.ecr.ap-southeast-1.amazonaws.com/laraveldemo-nginx:${CODEBUILD_RESOLVED_SOURCE_VERSION}
        - docker push 813995029960.dkr.ecr.ap-southeast-1.amazonaws.com/laraveldemo-php:${CODEBUILD_RESOLVED_SOURCE_VERSION}
        - docker push 813995029960.dkr.ecr.ap-southeast-1.amazonaws.com/laraveldemo-nginx:${CODEBUILD_RESOLVED_SOURCE_VERSION}
        - sed -e "s|<GIT_TAG>|$CODEBUILD_RESOLVED_SOURCE_VERSION|g" ./codedeploy/taskdef_template.json > ./codedeploy/taskdef.json
        - TASK_DEFINITION=`aws ecs register-task-definition --region ap-southeast-1  --cli-input-json file://codedeploy/taskdef.json | jq ".taskDefinition.taskDefinitionArn"`
        - sed -e "s|<TASK_DEFINITION>|$TASK_DEFINITION|g" ./codedeploy/appspec_template.yaml > ./codedeploy/appspec.yaml
artifacts:
    files:
    - codedeploy/appspec.yaml
    discard-paths: yes

