# This is an example to build the file buildspect.yml
version: 0.2
phases:
    install:
        runtime-versions:
            docker: 20
    pre_build:
        commands:
        - echo "Adding dependencies"
        - yum -y install zip awscli jq
        - docker-compose --version
        - printenv
        - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com
    build:
        commands:
        - make build_base_ci
        - make build_php
        - make build_nginx
    post_build:
        commands:
        - docker tag laraveldemo_php ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/PROJECT_NAME-SHORT_ENV-laravel-demo-php:${CODEBUILD_RESOLVED_SOURCE_VERSION}
        - docker tag laraveldemo_nginx ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/PROJECT_NAME-SHORT_ENV-laravel-demo-nginx:${CODEBUILD_RESOLVED_SOURCE_VERSION}
        - docker push ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/PROJECT_NAME-SHORT_ENV-laravel-demo-php:${CODEBUILD_RESOLVED_SOURCE_VERSION}
        - docker push ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/PROJECT_NAME-SHORT_ENV-laravel-demo-nginx:${CODEBUILD_RESOLVED_SOURCE_VERSION}
        - sed -e "s|<GIT_TAG>|$CODEBUILD_RESOLVED_SOURCE_VERSION|g" ./codedeploy/taskdef_template.json > ./codedeploy/taskdef.json
        - TASK_DEFINITION=`aws ecs register-task-definition --region ap-southeast-1  --cli-input-json file://codedeploy/taskdef.json | jq ".taskDefinition.taskDefinitionArn"`
        - sed -e "s|<TASK_DEFINITION>|$TASK_DEFINITION|g" ./codedeploy/appspec_template.yaml > ./codedeploy/appspec.yaml
artifacts:
    files:
    - codedeploy/appspec.yaml
    discard-paths: yes

